Feature/INESRP-113_Improve_GCov_plugin_overall_coverage_validation_2
zaleos/Ceedling pull request #9
Opened 2019-12-12 16:59 UTC by danielmartinezruiz

Related to https://github.com/zaleos/Ceedling/pull/7 using a stable branch.

2019-12-13 16:04 UTC, tobyjwebb requested changes

2019-12-13 16:04 UTC, tobyjwebb commented on plugins/gcov/gcov.rake
> +    if fail_under_line + fail_under_branch > 0
Readability issue?
I would use:
if fail_under_line > 0 or fail_under_branch > 0

2019-12-13 16:06 UTC, tobyjwebb commented
Oh, wait... No unit tests?

2019-12-16 11:25 UTC, danielmartinezruiz commented on plugins/gcov/README.md
> +files and exit Ceedling with an error. Use the following config; both are
Done the first one.

The second one I think it is not needed, cause all Ceedling (and coverture) are for CI processes.

2019-12-16 11:33 UTC, danielmartinezruiz commented on plugins/gcov/gcov.rake
> +    if fail_under_line + fail_under_branch > 0
Refactored.

2019-12-16 13:12 UTC, tobyjwebb approved these changes

2019-12-18 14:09 UTC, danielmartinezruiz commented
As someone did this open-source work on the upstream, it has no sense to keep this branch/PR

2019-12-18 14:09 UTC, closed without merging